---
title: "Squash Standings"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}


#Pull in Relevant Libraries
library(koboloadeR)
library(plotly)
library(ggplot2)
library(tidyverse)
library(tidyr)
library(elo)

###Get the data

#Create the Initial Dataframe pulling from Kobo Server (KoboloadeR package)
df<-kobo_data_downloader(formid = "200566",user = "spurious_hound:squashpw",api = "https://kc.humanitarianresponse.info/api/v1/")

#Compute the difference in scores
df<-df %>% mutate(windiff=WinScore-LosScore,
                  game=1:n())


#
winstable<-df %>% group_by(Winner) %>%
  summarise(Wins=n())


Winner<-df %>% rename(Name=Winner)%>% group_by(Name) %>%
  summarise(Wins=n())

Loser<-df %>% rename(Name=Loser)%>% group_by(Name) %>%
  summarise(Losses=n())

record<-full_join(x=Winner,y=Loser,by="Name")




pone<-df %>% rename(Name=Winner)%>% group_by(Name) %>%
  summarise(Points_For=sum(WinScore),
            Points_Against=sum(LosScore))


ptwo<-df %>% rename(Name=Loser)%>% group_by(Name) %>%
  summarise(Points_For=sum(LosScore),
            Points_Against=sum(WinScore))


#Calculate ELOS Scores
#Run ELos Scoring Function
eloscores<-elo.run(score(WinScore,LosScore)~Winner+Loser,data=df,k=20)


scores<-as.data.frame(final.elos(eloscores))


scores$Name<-rownames(scores)


final<-rbind(pone,ptwo) %>% group_by(Name) %>%
  summarise(Points_For=sum(Points_For),
            Points_Against=sum(Points_Against)) %>% full_join(record,by="Name") %>% arrange(desc(Wins)) %>%
  replace_na(list(Wins=0,Losses=0)) %>% mutate(Win_Pct=paste((round(Wins/(Wins+Losses),2)) * 100,"%")) %>% select(Name, Wins, Losses, Win_Pct,Points_For, Points_Against) %>% full_join(scores,by="Name") %>% rename(Score=`final.elos(eloscores)`)

  
```

Column {data-width=600}
---------------------------
###Record
```{r chart, echo=FALSE}

renderPlotly({
    newdata<-selectedData()
    
    f1 <- list(
      family = "Arial, sans-serif",
      size = 18,
      color = "lightgrey"
    )
    f2 <- list(
      family = "Old Standard TT, serif",
      size = 14,
      color = "black"
    )
    a <- list(
      title = "Score Differential",
      titlefont = f1,
      showticklabels = TRUE,
      tickangle = 45,
      tickfont = f2,
      exponentformat = "E",
      range=c(-15,15)
    )
    
    b <- list(
      title = "Date",
      titlefont = f1,
      showline=FALSE,
      showticklabels = FALSE,
      tickangle = 45,
      tickfont = f2,
      exponentformat = "E"
    )
    
    p <- plot_ly(data = newdata, x = ~game, y = ~windiff,color=~Winner,colors="Set1", hoverinfo = 'text',
    text=~paste(survey_day,HTML("<br>"),"Winner: ",Winner,", ",HTML("<br>"),"Loser: ", Loser,", ",HTML("<br>"), "Differential: ",windiff,sep = ""), marker=list(size=10)) %>%
      layout(xaxis = b, yaxis = a)
    
    p
  })
 
```

Column {data-width=400}
---------------------------
```{r}

renderDataTable(final)

```

###Subsets
```{r}
checkboxGroupInput(inputId = "players",label="Players",
            choices = unique(c(df$Winner,df$Loser)),selected = "NULL")


selectedData <- reactive({
    
  if(is.null(input$players)){
    df
  } else{
    df[df$Winner==as.character(input$players) | df$Loser==as.character(input$players),]
  }

})

renderTable(selectedData())

```


